### ISSUE TITLE
本demo中echarts.js无法显示title和legend

### ISSUE THREAD

**Issue by xiaohui96** [yapeee/dynamic-echarts-demo#1]
您好，引入该demo中的echarts.js无法实现显示图表的title和legend，官方的echarts.js可以显示，但文件太大超出小程序要求的2M

**Comment by yapeee** [comment]
echarts官网可以选择自定义下载，自由选择所需要的图标和组件

**Comment by hubo802** [comment]
您好，我官网下载的配置（为了提示框）一到  Chart.clear(); 就挂了，本例里面的echarts.js就没有问题，官网下载配置的时候有什么需要注意的吗

**Comment by yapeee** [comment]
@hubo802  您好，我更新了一版官网提供的能够支持Tooltip的echarts.js，你试一下可行不可行？现在官网中自己配置的echarts暂不支持Tooltip。

**Comment by hubo802** [comment]
感谢，我这边试一下
Cannot read property 'hide' of undefined; [Component] Event Handler Error @ pages/statistics/statistics#bound changetype
TypeError: Cannot read property 'hide' of undefined
如不点击加载好的图去触发提示框，直接切换数据调用clear()这步还是会报错

**Comment by yapeee** [comment]
> 感谢，我这边试一下
> Cannot read property 'hide' of undefined; [Component] Event Handler Error @ pages/statistics/statistics#bound changetype
> TypeError: Cannot read property 'hide' of undefined
> 如不点击加载好的图去触发提示框，直接切换数据调用clear()这步还是会报错

去掉`Chart.clear();`即可，目前应该是echarts.js文件存在bug

**Comment by hubo802** [comment]
> 。去掉Chart.clear();即可，目前应该是echarts.js文件存在bug

官网的echarts.js目前有这个bug，如去掉Chart.clear();条形切换扇形会导致坐标轴不清除。最后只能把提示框数据简化后放在图形区域上了，暂时还是用您这边老版的那个JS
